name: release
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: blazemeter_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version
        id: version
        run: echo "release_version=2.5" >> $GITHUB_ENV

      - name: setup ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Create jmeter-plugins pull request
        run: ./.github/jmeter_plugins_pr.sh
        env:
          RELEASE_VERSION: ${{ env.release_version }}
          PLUGIN_ARTIFACT_NAME: "jmeter-bzm-correlation-recorder"
          PLUGIN_REPOSITORY_NAME: "CorrelationRecorder"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
